- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    state: present

- name: Install base apt packages
  ansible.builtin.apt:
    name:
      - g++
      - automake
      - cmake
      - libtool
      - autoconf
      - software-properties-common
      - gnupg
      - ca-certificates
      - lsb-release
      - apt-transport-https
      - coreutils # GNU File, Shell, and Text utilities
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - cargo
      - zsh
      - snapd
      - python3-pip
      - nodejs
      - unzip
      - ruby-neovim
    state: present
