- name: Install "argc" Rust package
  shell: cargo install --git https://github.com/sigoden/argc.git --tag v0.8.2

- name: Update Rust packages to its latest version
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  loop:
    - stylua
    - vivid
