- hosts: localhost
  name: Setup Ubuntu
  become: false
  remote_user: liveonit
  environment:
    HOME: "/home/{{ ansible_user }}"
  tasks:
    - name: Install node environment and its packages
      ansible.builtin.include_tasks: tasks/node.yml
