- hosts: localhost
  become: yes
  remote_user: admin
  environment:
    HOME: "/home/{{ ansible_user }}"
  pre_tasks:
    - name: Update Apt
      apt:
        update_cache: true
        state: present
  tasks:
    - include: tasks/apt.yml
    - include: tasks/custom-installations.yml
    - include: tasks/node.yml
    - include: tasks/python.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/dotfiles.yml
